ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'UPDATE_ROOM_STATUS';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'CREATE_ROOM_TYPE';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'UPDATE_ROOM_TYPE';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'DISABLE_ROOM_TYPE';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'CREATE_AMENITY';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'UPDATE_AMENITY';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'DISABLE_AMENITY';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'CREATE_REGION';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'UPDATE_REGION';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'DISABLE_REGION';

ALTER TABLE "RoomType" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Amenity" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Region" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
